const products = [
  {
    id: 1,
    name: "iPhone 12 comun",
    images: "../assets/12comun.jpg",
    description: "Iphone 12 64gb - libre de fabrica",
    stock: 5,
    price: 100000,
    shippment: "Gratis",
    status: "Nuevo",
  },
  {
    id: 2,
    name: "iPhone 12 mini",
    images: "../assets/12mini.jpg",
    description: "Iphone 12 mini 128gb - Empresa personal",
    stock: 5,
    price: 80000,
    shippment: "$2000",
    status: "Usado",
  },
  {
    id: 3,
    name: "iPhone 13 comun",
    images: "../assets/13comun.jpg",
    description: "Iphone 13 comun 256gb - libre de fabrica",
    stock: 3,
    price: 300000,
    shippment: "Gratis",
    status: "Nuevo",
  },
  {
    id: 4,
    name: "iPhone 13 mini",
    images: "../assets/13mini.jpg",
    description: "Iphone 13 mini 256gb libre de fabrica ",
    stock: 3,
    price: 250000,
    shippment: "Gratis",
    status: "Nuevo",
  },
  {
    id: 5,
    name: "MacBook Pro 14 M1 Pro",
    images: "../assets/macbook.jpg",
    description: "512 GB - Gris Espacial (Space Gray)",
    stock: 5,
    price: 700000,
    shippment: "$3000",
    status: "Nuevo",
  },
  {
    id: 6,
    name: "iPad Pro 12.9 M1",
    images: "../assets/ipad.jpg",
    description: "WiFi + 4G 2TB - Gris Espacial (Space Gray) (2021)",
    stock: 2,
    price: 80000,
    shippment: "$2000",
    status: "Usado",
  },
  {
    id: 7,
    name: "iMac 24 M1",
    images: "../assets/mac.jpg",
    description: "8C CPU 8C GPU 256 GB - Verde (Green)",
    stock: 1,
    price: 50000,
    shippment: "Gratis",
    status: "Nuevo",
  },
  {
    id: 8,
    name: "Apple Airpods Pro",
    images: "../assets/airpro.jpg",
    description: "Incluye caja de carga MagSafe",
    stock: 2,
    price: 50000,
    shippment: "$1000",
    status: "Nuevo",
  },
];

export default products;
